### ISSUE TITLE
emoji / unicode not printing correctly on mood generator materials

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1015]
![Screen Shot 2022-06-29 at 4 20 44 PM](https://user-images.githubusercontent.com/66691020/176546976-a2e96fd1-6306-4721-ad41-1ce05c8879b5.png)
![Screen Shot 2022-06-29 at 4 20 54 PM](https://user-images.githubusercontent.com/66691020/176546980-b92c5ee0-a8f4-4077-b817-92789603c6ed.png)

instead of emoji, we're seeing dots and unicode identifiers.

This is from the piecewise functions lesson.

**Comment by schanzer** [comment]
@ds26gte here's what I see now
<img width="930" alt="image" src="https://user-images.githubusercontent.com/77126/176783055-57b362e0-93f2-43af-bcc0-1537573bba2a.png">

Note that the results have quotes in the definition, but not the examples! And the 'sick' emoji shows up correctly in the examples, but not in the definition.

**Comment by ds26gte** [comment]
I just fixed this (8 min before you wrote this), but the bigger problem may be the inability of the PDF converter to preserver any high-value Unicode characters at all. Thus all of these face emojis become black bullets in the PDF. We need to think about manually replacing such emojis into images before passing them on to puppeteer

**Comment by schanzer** [comment]
@ds26gte still not seeing quotes around the emojis in the examples. Noted re: PDFs

**Comment by ds26gte** [comment]
Pushed suggested fix in 5443a4de.

If the example RHS is a string in a Pyret DR is a string, check if it has a newline or at least 2 spaces. If so, then view it as a Pyret code fragment. Otherwise it's a Pyret string literal.

**Comment by schanzer** [comment]
@ds26gte here's the PDF for WeScheme after a fresh pull (still seeing unicode string):
[mood-generator-dr.pdf](https://github.com/bootstrapworld/curriculum/files/9035722/mood-generator-dr.pdf)

**Comment by ds26gte** [comment]
I want to formally retract my concern about emojis not showing in the PDF. It seems to be depend purely on the capabilities of the PDF viewer used, not on the PDF file itself. The emojis don't show up in the `evince` viewer on my box, but show up fine on the `okular` viewer. And I suspect you as mac users never run into this problem at all.

**Comment by schanzer** [comment]
This is now fixed
