### ISSUE TITLE
Cleanup of Optional directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1438]
Spec from @retabak and @flannery-denny 

`@opt{text.}` 
- should read inline as: 
 _Optional:_ text.

`@opt{@project{infographic.adoc, rubric-infographic.adoc}}` should work just like `@opt-project`
- Inline looks as follows:
 _Optional Project:_ Making Infographics [_rubric_]
- Materials section (first in the list of optional items) looks as follows: 
 _Optional Project:_ Making Infographics [_rubric_]
- Added to the Teacher Resource page
- Appear as a button on the build your own pathway page

`@opt{@starter-file{x}}` should work like `@opt-starter-file{x}`.
- Inline the link reads as:
  x
- Materials section (listed directly beneath `@opt{@project{}}`) the link is listed as: 
 _Optional:_ x 

`@opt{@printable-exercise{page.adoc}}` should work just like `@opt-printable-exercise{page.adoc}`
- Inline it should appear the same as `@printable-exercise{page.adoc}` as a link that reads: 
  page  
- Materials section (appears beneath `@opt{@project{}}` items) should say: 
 _Optional:_ page 

`@opt{@online-exercise{page.adoc}}` should work just like `@opt-online-exercise{page.adoc}`
- Inline it should appear the same as `@printable-exercise{page.adoc}`as a link that reads: 
 page 
- Materials section (beneath `@opt{@printable-exercise{}}` items) and should say: 
 _Optional:_ page

**Lessons Table:**

- @starter-file
- Pages from the Student Workbook:
- @printable-exercise
- @online-exercise
- @handout
- @opt{@project}
- @opt{@starter-file}
- @opt{@printable-exercise}
- @opt{@online-exercise}

**Comment by retabak** [comment]
wait wait wait, I flagged this a while ago! And Emmanuel fixed it. But perhaps more have crept in? Let me see if I can find the issue.

**Comment by retabak** [comment]
It was issue #1121, fixed with this commit: https://github.com/bootstrapworld/curriculum/commit/d05e7cb6c57beb4363d5daca3f00b1ee8be2c493

We went with Optional.

**Comment by flannery-denny** [comment]
Interesting. A quick find in files reveals at least 4 other formats... including stuff written today. I think that makes the case stronger that we should have a directive.

**Comment by flannery-denny** [comment]
I just removed all instances of OPTIONAL, but I'm still seeing

- Optional
- _Optional_
- **Optional**

Personally, I prefer _Optional_ and would like to see and @opt{} directive that makes that formatting consistent.

**Comment by retabak** [comment]
I like this proposal.

**Comment by schanzer** [comment]
In that case, I'd like to see us get rid of `@opt-XYZ{}` for handouts, online-exercises and printable-exercises. We should be able to infer this from their appearance within `@optional{}`, instead of littering our list of directives.

**Comment by ds26gte** [comment]
So `@opt` simply prefixes its contents with `Optional: `, or perhaps encloses them in a class `.optional` that can then be styled via CSS?

**Comment by schanzer** [comment]
Yes, but the processing of child directives treats them as if they were prefixed with `opt-`

**Comment by ds26gte** [comment]
Will there be an "Optional" prefixing the `@opt`'s argument, and also individual "Optional" prefixes for each of the relevant directives within it? That seems like a lot of "Optional" annotations.

**Comment by schanzer** [comment]
I am literally asking for no prefixes at all:

> Yes, but the processing of child directives treats them as if they were prefixed with `opt-`

**Comment by ds26gte** [comment]
In which case, we can simplify things further: The `@opt` encloses its argument in an `.Optional` class (and does nothing else), and you use CSS selectors to convert `.PrintableExercise` and the like to insert the "Optional" prefix only when they're enclosed in the `.Optional` class.

**Comment by schanzer** [comment]
Exactly! But my concern is the preprocessing that happens. Are still able to generate the right dependency graph and do all the same error checking, if now every single page is `@printable-exercise`?

**Comment by ds26gte** [comment]
Yes, optional printable-exericse, &c, continue to have their separate bookkeeping. Please see branch `new-opt-directive` to try out the new `@opt` directive.

For continuity, I've retained the original `@opt-XXX` directives, but they will be phased out once `@opt{  ... @printable-exercise{...} ... }` is found to be satisfactory in all respects.

Note `@opt` introduces the CSS class `.OptionalStretch` around its entire argument. This needs to be given appropriate meaning via CSS.

**Comment by flannery-denny** [comment]
@schanzer I understand that you have a desire to keep directives to a minimum, but, honestly, what we've requested here is pretty different from the three existing optional directives (`@opt-printable-exercise`,`@opt-online-exercise` and `@opt-project`) that are currently doing exactly what we want them to. 

Those three directives are quite different from each other and from what is proposed for `@opt`. 

Your request for this directive to subsume the others has made this issue much more complicated and I think unnecessarily so. 

Please let us know before our meeting tomorrow whether it's ok for us to get the requested directive working as we want (it's sole purpose is to unify styling in the text since authors are currently choosing their own at whim and it's causing repeated messes to clean) or whether we need to incorporate a much much larger spec to meet your request to eliminate other directives. Thanks!

**Comment by schanzer** [comment]
@flannery-denny The fact that we have different ways of writing "optional:" is not causing major problems for anyone, and directive clutter is definitely becoming an issue. I'd like to think this through holistically instead of rushing towards a narrow solution - especially if we may wind up changing that solution anyway when we have time to think it through.

**Comment by flannery-denny** [comment]
@schanzer @retabak and I met to draft a spec to discuss with Dorai tomorrow. Please have a look at the issue description and let us know if there is anything you would amend.

**Comment by schanzer** [comment]
Also, I'm curious: why can't we just find-and-replace to get these in line? Why are we building directives and having meetings about something that is literally a 10sec find-and-replace?

**Comment by schanzer** [comment]
@flannery-denny yes, this spec is exactly what I had in mind. That being said, I'm still wondering if this is worth all the time given that it's a find-and-replace.

**Comment by flannery-denny** [comment]
@schanzer In our meeting today Dorai confirmed that he could create an `@opt` directive to subsume all of the prefixes, but it would not be able to also meet the needs that led this issue to be created. Therefore, we have  implemented the `@optional` directive. In that you weren't sure that the other aspects were worth our time, I am going to close the issue. If, you would like to see energy spent on making an `@opt` directive to replace prefixes, feel free to reopen.

**Comment by schanzer** [comment]
@ds26gte Flannery and I spoke, and we'd like to implement this so that @opt{.....prose...} gets the nifty CSS "optional:" prefix _and_ that any prose containing @printable-exercise and @online-exercise has them treated as their `@opt-` equivalents. We're going to punt on this until the Spring, so no action needed for now.

**Comment by flannery-denny** [comment]
also, when this gets implemented, there may be some feedback loop that warns when `@opt-printable-exercise` is used without `@optional`

**Comment by schanzer** [comment]
Well, we won't even _have_ `@opt-printable-exercise` anymore, so the warning will be "unknown directive"!

**Comment by ds26gte** [comment]
Assuming y'all want the directive named `@opt` not `@optional`? (You have used both names in your recent messages.)

I'm sure @schanzer at least doesn't want both (as aliases of each other). :-)

**Comment by schanzer** [comment]
No preference! `@opt` works for me!

**Comment by ds26gte** [comment]
One more thing: Is the new `@opt{ ... }` always guaranteed to be used in a block position, as opposed to in-text (e.g., within an English sentence)?

**Comment by schanzer** [comment]
@ds26gte never in the middle of a sentence, but absolutely at the start of a bullet. We should support the following asciidoc:
```
- do something
- do something else
- @opt{try this other thing}
```

**Comment by ds26gte** [comment]
Note: The previous `@optional` directive that simply outputs _Optional:_ in italics is still in place because @flannery-denny  is using it in many files. The UI difference between `@optional` and the new `@opt` is that the former requires no argument and the latter does.

Once you're both satisfied, I can do a global replace of all occurrences of `@optional` to `@opt{}` and then consign the `@optional` directive to oblivion.

**Comment by schanzer** [comment]
@ds26gte ah, the use of a different directive makes this have the same opt-in impact as a separate branch. That works for me!

**Comment by ds26gte** [comment]
Yeah, existing code using the older style (including the fairly new `@optional) is unaffected.  Opt-in (no pun intended)!

**Comment by ds26gte** [comment]
> @ds26gte never in the middle of a sentence, but absolutely at the start of a bullet. We should support the following asciidoc:
> 
> ```
> - do something
> - do something else
> - @opt{try this other thing}
> ```

In my implementation, you should be able to use `@opt{...}` anywhere, around one or more blocks, or in-text.

**Comment by flannery-denny** [comment]
Noting that we still have some work to do around deploying `@optional`. Just found this inconsistency in the contracts: making tables and displays lesson. 
<img width="860" alt="Screen Shot 2023-08-25 at 10 39 33 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c30b1e57-e5f0-49f7-bc46-269e9c363940">


Deploying `@optional` to make it looks like this.
<img width="839" alt="Screen Shot 2023-08-25 at 10 40 40 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/28fa0e77-b96d-4267-81e9-133a2649c91f">

**Comment by ds26gte** [comment]
What is desired here?
