### ISSUE TITLE
Replace @optional with @opt{...}

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1761]
@flannery-denny I'm rewriting the issue description now that Dorai has weighed in about `@opt{...}`, which does exactly what we want.

- [ ] Replace all instances of `@optional XYZ` with `@opt{XYZ}` - FD
- [ ] remove @optional
- [x] Change slide-preproc behavior so that `@opt{XYZ}` hardcodes the slide text _Optional:_ XYZ - DS
- [x] Change lesson-preproc behavior so that `@opt{XYZ}` generates a DIV with class `.optional` - DS
- [x] Add CSS rule to insert _Optional:_ at the start of the div content, mirror the current behavior of `@optional` - ES

Note: this should happen on a separate branch, as it will almost certainly need a few rounds of commits and checks before it's "right"

---------------------------------------

Currently we have `@optional` and it does exactly what we want it to do in lesson plans... insert  _"Optional:"_
but when it comes to building slides the directive is not robust enough.

`@optional{}` will do exactly what `@optional` has been doing everywhere except for slides.

In slides `@optional{}` will put  _"Optional:"_ and all of the text inside the `{}` in the presenter notes section.

This spec has already been approved by Emmanuel.

Please let Flannery do the find and replace - it will be delicate...

**Comment by flannery-denny** [comment]
@retabak this impacts your writing a little bit. You have a few instances in Early Math where you wrote

> - Ready for a challenge? @optional Try @opt-printable-exercise{associativity-makes-comp-easier-challenge.adoc} to apply the evaluate expressions with fractions and decimals.

Directions like these will instead have to begin with `@optional`, e.g.

>  - @optional If you're ready for a challenge, try @opt-printable-exercise{associativity-makes-comp-easier-challenge.adoc} to apply the evaluate expressions with fractions and decimals.

**Comment by ds26gte** [comment]
After scanning multiple branches, it appears that the current implementation of `@optional` does _not_ take an argument. We do have a directive `@opt` that does take an argument.

For slides, we don't have suitable definitions for either `@optional` or `@opt`. Is there a consensus on what the name of this directive should be? If it is to be `@optional`, a lot of existing files should be carefully rewritten.

**Comment by flannery-denny** [comment]
@schanzer I've tested out `@opt{}` in bar-and-pie-charts. It looks great in slides. Formatting is off in the lesson plan. Currently looks like this
<img width="628" alt="Screen Shot 2024-01-22 at 8 15 38 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c3508bd7-822f-4bde-9ac8-71ea80d90d13">

**Comment by schanzer** [comment]
@flannery-denny I've just pushed an update should resolve the display of @opt in lessons. Confirming it fixes the (super helpful) bar-and-pie-charts lesson example you shared.

**Comment by flannery-denny** [comment]
Better, but not quite there. Still seeing the -- --
<img width="511" alt="Screen Shot 2024-01-22 at 9 15 07 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/572a7eb8-5992-4a40-b476-112f6650c9f6">

**Comment by flannery-denny** [comment]
@schanzer Also seeing this in contracts-tables-displays

`@opt{If your students would benefit from seeing a few more examples before drawing their own Circles of Evaluation, have them @opt-printable-exercise{matching-coe-to-descriptions.adoc}.}`
<img width="807" alt="Screen Shot 2024-01-22 at 9 20 12 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/cf763b9c-8836-4b9f-bfcb-434a933feade">

**Comment by flannery-denny** [comment]
Looks good! I'm going to close this issue, since implementing this in lesson plans is just part of #1669
