### ISSUE TITLE
Spellchecker improvements

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2458]
The spellchecker starts by slurping in the entire text of an adoc file as a giant string. It then splits the string on whitespace, and does some filtering of words.

This could be smarter! We want it to:

- [x] Strip out anything between `<style>` and `</style>`
- [x] Strip out anything between backticks and triple-backticks
- [x] Strip out roughnum literals: `~\d+`
- [x] Strip out mathjax: `@math{...}`
- [x] Strip out sexprs: `@show{...}` and `@showsoln{...}`
- [x] Strip out links: `@link{...}`

The existing JS file does _some_ of these, but could/should be doing more.

**Comment by ds26gte** [comment]
Commits c546f37  3da9b03  d1931e8  9af215c address these.

**Comment by flannery-denny** [comment]
@ds26gte you seem to be stripping out some extra characters. I've merged master into `periodics` and when I just tried to commit my updates to the quadratics3 lesson it returned the following list.

> WARNING: lessons/Algebra2/quadratic3-fitting-models/langs/en-us/index.adoc may have spelling errors in the following words: certn, ple, Quaatic, kely, los, Sde, Sdes, dicting, quaatic, intert, dicts, fficients, ne, aaron, hiistance, batangle, quaatics, nk, sders, aeady

When I search for these strings in the file to fix them, they aren't there

**Comment by ds26gte** [comment]
Hmm, I don't strip anything destructively from the .adoc files. The strings are merely removed from an in-memory copy before being sent to the Hunspell spellchecker.  This is still an error because it seems like it could be removing the prefixes of legit words -- if you could slack/email me the index.adoc, if you have it, I can inspect it.

**Comment by ds26gte** [comment]
(Also: Do one `make` (even if it seems pointless) before attempting a commit. This will install the latest spell-check hook in your `.git`, which can only be done by a user action.)

**Comment by ds26gte** [comment]
I'm trying feeding the entire file to see if the spellchecker mangles the words and announces them as misspellings. Not seeing it. Which branch, and which file (if already pushed), expose this error? I can see if I can create a separate clone and re-commit to see what's happening.

**Comment by schanzer** [comment]
@flannery-denny I'm not able to replicate these mangled words. Is this happening even after a `make clean`? Maybe you and Dorai need to hop on zoom

**Comment by schanzer** [comment]
@flannery-denny nevermind - we found the issue. Partial fix already in place. Working with Dorai on finishing it

**Comment by schanzer** [comment]
@flannery-denny Dorai and I have spent a bunch of time testing and refining this. I think it's ready to close, but you should test it first. Try turning it loose on an entire lesson, following this example:

`./spell-check-file lessons/Algebra2/exponential3-fitting-models/langs/en-us/index.adoc`

**Comment by flannery-denny** [comment]
WARNING: lessons/Algebra2/quadratic4-other-forms/langs/en-us/index.adoc may have spelling errors in the following words:  nbsp

We use `{nbsp}` all the time. It shouldn't throw warnings.

**Comment by flannery-denny** [comment]
Spellchecker is vastly improved! And I have merged many times today. And made force. 

But I'm still seeing this warning

`WARNING: lessons/Algebra2/exponential3-fitting-models/langs/en-us/pages/exponential-models-ma.adoc may have spelling errors in the following words:  nbsp`

**Comment by schanzer** [comment]
@flannery-denny not sure what `git-ignored.json` is, but this is now resolved

**Comment by ds26gte** [comment]
Actually, adding `nbsp` and `{nbsp}` doesn't solve the real problem. `nbsp` was already in the ignore list.

The bug is quite subtle and happens because Lua's cheap-but-efficient patterns wouldn't let me recognize word boundaries, or so I thought. Ordinarily this isn't a problem, because I took care that the words were separated by spaces, and I could search for enclosing spaces easily enough. However, when an ignored word occurs consecutively, as in Flannery's example where after various transformations two `nbsp`s suddenly become consecutive, there's only one space separating them, and only one of the `nbsp`s gets removed.

The bug is now fixed (commit 0d26fbf) using Lua's little-known _frontier_ pattern `%f`, which I found out about only today in response to this problem. I'm sure this is not really super interesting, and you just wanted the problem fixed, but kudos to @flannery-denny  for finding an excellent edge case that is almost impossible to predict!
