### ISSUE TITLE
BSA:Orderofoperations

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#8]
- [x] `pi` is used here, but the symbol is used in the subsequent lesson. Which one is it?
- [x]  (Promoted from comment below) shouldn't the "strategies for learners" section be formatted specially, as it is in other lessons?
- [x] Lesson goals is blank
- [x] Images use the wrong font - where are these taken from?
- [x] WeScheme.org link is leaking asciidoc formatting
- [x] Asciidoc tags leaking through, and broken images ![image](https://user-images.githubusercontent.com/77126/56448207-5e3e1e80-62db-11e9-991b-affd2eb7fe5d.png)
- [x] need spaces before parentheticals, and functions should be formatted as code. ![image](https://user-images.githubusercontent.com/77126/56448222-744bdf00-62db-11e9-9549-7a145c55256b.png) 
![image](https://user-images.githubusercontent.com/77126/56448232-7e6ddd80-62db-11e9-83d6-31f1ccafbc2f.png)
- [x] Should these be links? ![image](https://user-images.githubusercontent.com/77126/56448243-904f8080-62db-11e9-96e1-fcc664ae6cf6.png)

**Comment by edcamposjr22** [comment]
Fixed the spaces and code formatting.

**Comment by schanzer** [comment]
Code formatting is not fixed. I see asciidoc directives in multiple places, including `== Big Idea of lesson goes here` at the top. Please don't close this until it's done.

**Comment by schanzer** [comment]
Also, shouldn't the "strategies for learners" section be formatted specially, as it is in other lessons?

**Comment by edcamposjr22** [comment]
Formatted the 'Strategies for Learners' and changed it to an MLR 7 'Connect & Compare'
Fixed WeScheme link from leaking.
Replaced Images with new ones that have Century Gothic font.
