### ISSUE TITLE
Wescheme Solutions Workbook Issues to fix

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#972]
This is a running list of things needing bigger attention. There are lots of small things FD will fix. 

- [x] p 14 Complete-code-from-coe is missing solutions - FD isn't sure how to include them with the way this page is formatted
- [x] p 17 code should never be revealed as **frac** - @ds26gte use **/** instead `lessons/order-of-operations/pages/translate-arithmetic-to-circles-and-code-challenge`
- [x] p22 Fix typos in domain & range frayer model pdf
![Screen Shot 2022-06-19 at 2 11 19 PM](https://user-images.githubusercontent.com/66691020/174496816-29bf7143-94ea-4c4a-9b4c-c2db77b979b1.png)

- [x] p29 Diagramming Function composition. Formatting is different for `@math{h(g(f(4))) = 17}` and `@showsoln{@math{g(f(h(4))) = 15}}`

- [x] p31, 32, 33 Solution code is being cut off vertically. `lessons/function-composition/function-composition-scale-xy`, `lessons/function-composition/function-composition-your-name`, `lessons/function-composition/more-than-one-way`

![Screen Shot 2022-06-18 at 9 13 58 AM](https://user-images.githubusercontent.com/66691020/174442363-a7c02c4d-3ea7-4767-91cc-631d0793d6ab.png)

- [x] p44, 45, 46 `functions-make-life-easier/pages/rs` , `functions-make-life-easier/pages/sun` ,  `functions-make-life-easier/pages/define-your-own` are missing solutions and showing ascii code in the solutions - not sure what the code would be to get these building correctly
- [x] decide whether it's ok that solution pages do not have solution images.
- [x] p 61 @ds26gte code for contracts is printing `>` instead of `-->` on `functions-examples-definitions/create-contracts-examples`
- [x] p107 challenges for update player - I'm not sure what's supposed to be happening here... but I'm pretty sure the solutions aren't right.

**Comment by flannery-denny** [comment]
@flannery-denny use rs as a model for adding solutions to `sun`

**Comment by schanzer** [comment]
@flannery-denny I believe I've addressed the remaining bullets. Some of these formatting changes were VERY difficult, but the exercise gave me some good ideas for how things can be cleaned up in the coming year as part of a bigger CSS change. 

Close if you're happy with what you see?

**Comment by flannery-denny** [comment]
@schanzer this is a huge improvement. I'm noticing that:

- the bottom question on `function-composition/more-than-one-way` is still getting cut off. Perhaps it could be fixed if the solution were placed on the @fitb below?

Close if you can resolve  that.

**Comment by schanzer** [comment]
[more-than-one-way.pdf](https://github.com/bootstrapworld/curriculum/files/8962743/more-than-one-way.pdf)

@flannery-denny Here's the PDF I get from that file. Nothing is cut off. Can you send me what you're seeing?

**Comment by flannery-denny** [comment]
[more-than-one-way.pdf](https://github.com/bootstrapworld/curriculum/files/8962992/more-than-one-way.pdf)
here's what I get for the pyret version

**Comment by schanzer** [comment]
@flannery-denny interesting! Your system seems to have different fonts than mine. Since I'm the one generating the workbooks, I think this is ok to close. We can work on getting our fonts lined up another time.
